"""Add date posted and closign date columns to Job model

Revision ID: 15607467301a
Revises: b46bcc1ee71e
Create Date: 2024-07-30 02:16:30.180359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15607467301a'
down_revision = 'b46bcc1ee71e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('closing_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('date_posted', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('date_posted')
        batch_op.drop_column('closing_date')

    # ### end Alembic commands ###
