"""Create Company model

Revision ID: 73cb8b6bf720
Revises: 87cba10e26b2
Create Date: 2024-07-26 17:24:49.335056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73cb8b6bf720'
down_revision = '87cba10e26b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('bsn', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('csr_tags', sa.String(), nullable=False),
    sa.Column('website_link', sa.String(), nullable=False),
    sa.Column('facebook_link', sa.String(), nullable=True),
    sa.Column('instagram_link', sa.String(), nullable=True),
    sa.Column('linkedin_link', sa.String(), nullable=True),
    sa.Column('admin_email', sa.String(), nullable=False),
    sa.Column('_hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('companies')
    # ### end Alembic commands ###
