"""Update Company model to rename column from BSN to ABN

Revision ID: b46bcc1ee71e
Revises: 5638287c50f5
Create Date: 2024-07-28 16:32:40.389415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b46bcc1ee71e'
down_revision = '5638287c50f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('abn', sa.Integer(), nullable=True))
        batch_op.drop_column('bsn')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bsn', sa.INTEGER(), nullable=True))
        batch_op.drop_column('abn')

    # ### end Alembic commands ###
