"""Add about column and remove csr_tags from Company

Revision ID: cb2f2bf41792
Revises: 15607467301a
Create Date: 2024-07-30 03:18:39.162127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb2f2bf41792'
down_revision = '15607467301a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_companies')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about', sa.String()))
        batch_op.drop_column('csr_tags')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('csr_tags', sa.VARCHAR()))
        batch_op.drop_column('about')


    # ### end Alembic commands ###
