"""Create Job model

Revision ID: fccb6bae492c
Revises: 73cb8b6bf720
Create Date: 2024-07-26 17:34:48.875634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fccb6bae492c'
down_revision = '73cb8b6bf720'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.Column('salary_comments', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('role_description', sa.String(), nullable=False),
    sa.Column('application_link', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('experience', sa.String(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('jobs')
    # ### end Alembic commands ###
